apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-keycloak-integration
  namespace: sso-integration
spec:
  template:
    spec:
      containers:
      - name: cluster-keycloak-integration
        image: quay.io/leoliu2011/cluster-keycloak-integration:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: argocd-configs
      restartPolicy: Never
  backoffLimit: 5