apiVersion: v1
data:
  ARGO_CLIENT_ID: "argocd"
  ARGO_GROUP_NAME: "ArgoCDAdmins"
  ARGO_ROOT_URL: "placeholder"
  HTTP_DEBUG: "false"
  TLS_VERIFY: "false"
  KEYCLOAK_HOSTNAME: "placeholder"
  MASTER_REALM: "master"
  PASSWORD: "placeholder"
  USER_NAME: "admin"
  # Microsoft Azure
  AZURE_CLIENT_ID: "urn:federation:MicrosoftOnline"
  AZURE_X509_CERT: "placeholder"
  # openshift brokering
  OPENSHIFT_BROKER_API_SERVER: "https://api.hub.mcm-aiops-gitops.ibmsbaasonaz.com:6443"
  OPENSHIFT_BROKER_DISPLAY_NAME: "Login with OpenShift"
  # Hub cluster
  CLUSTER_CLIENT_ID: "hub-cluster"
  OPENSHIFT_OAUTH_NAME: "keycloak3"
  CLUSTER_IS_ADMIN: "true"
   # aws
  AWS_CLIENT_SAML_URL: "https://signin.aws.amazon.com/static/saml-metadata.xml"
  AWS_ID_PRODIVER_NAME: "demo"
  AWS_IAM_ROLE_POLICY_ARN: "arn:aws:iam::aws:policy/ReadOnlyAccess"
  AWS_IAM_ROLE_NAME: "READ_ONLY_USER_ROLE"
  AWS_IAM_ROLE_SESSION_DURATION: "28800"
  KEYCLOAK_AWS_GROUP: "READ_ONLY_AWS_USERS"
kind: ConfigMap
metadata:
  name: argocd-configs
  namespace: sso-integration
  annotations:
    argocd.argoproj.io/hook: Skip
